version: '3.0'

services:
  statalon:
    image: engine-johnson-scanner:latest
    restart: always
    ports:
      - 80:80
    container_name: engine-johnson-scanner
    env_file:
      - prod.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_DB=cornell
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<pw>
    ports:
      - 5432:5432
    container_name: database-johnson-scanner
